name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run .NET Tests
        run: dotnet test -c Release --verbosity normal

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Angular Dependencies
        run: npm install
        working-directory: ./Blog.WebUi

      - name: Run Angular Tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: ./Blog.WebUi